<?php

return [
    'request_type' => [
        'estimate' => 1,
        'delivery' => 2,
    ],
    'request_detail_status' => [
        'new' => 1,
        'lock' => 9,
    ],
    'user_roles' => [
        'user' => 'user',
        'admin' => 'admin',
    ],
    'logo_status' => [
        'active' => 0,
        'stop' => 7,
        'sold_out' => 8,
        'negotiation' => 2,
        'deleted' => 9,
    ],
    'alphabets' => [
        1 => 'A',
        2 => 'B',
        3 => 'C',
        4 => 'D',
        5 => 'E',
        6 => 'F',
        7 => 'G',
        8 => 'H',
        9 => 'I',
        10 => 'J',
        11 => 'K',
        12 => 'L',
        13 => 'M',
        14 => 'N',
        15 => 'O',
        16 => 'P',
        17 => 'Q',
        18 => 'R',
        19 => 'S',
        20 => 'T',
        21 => 'U',
        22 => 'V',
        23 => 'W',
        24 => 'X',
        25 => 'Y',
        26 => 'Z',
        27 => '!',
        28 => '?',
        29 => '&',
        30 => '@',
    ],
    'payment_methods' => [
        1 => [
            'id' => 1,
            'name' => 'Credit Card Stripe',
            'type' => 1,
        ],
        2 => [
            'id' => 2,
            'name' => 'QR Scan',
            'type' => 2,
        ],
        3 => [
            'id' => 3,
            'name' => 'Mono',
            'type' => 3,
        ],
        4 => [
            'id' => 4,
            'name' => 'ZaloPay',
            'type' => 4,
        ],
    ],
    'mail_setting' => [
        'support@logotank.net',
    ],
];
