export default {
    SET_MENU: 'SET_MENU',
    SET_OPEN_MENU: 'SET_OPEN_MENU',
    SET_OPEN_MOBILE_MENU: 'SET_OPEN_MOBILE_MENU',
    SET_OPEN_SIGN_IN: 'SET_OPEN_SIGN_IN',
    SET_OPEN_SIGN_UP: 'SET_OPEN_SIGN_UP',

    SET_OPEN_PAYMENT_METHOD: 'SET_OPEN_PAYMENT_METHOD',
    SET_PREPARE_ORDER_DATA: 'SET_PREPARE_ORDER_DATA',
    SET_LOADING: 'SET_LOADING',

    SET_DESIGNERS: 'SET_DESIGNERS',

    REQUEST_ESTIMATE: 1,
    REQUEST_DELIVERY: 2,

    SET_UNITS: 'SET_UNITS',
    SET_MERCHANTS: 'SET_MERCHANTS',
    SET_VENDORS: 'SET_VENDORS',

    UPDATE_ITEM: 'UPDATE_ITEM',
    DELETE_ITEM: 'DELETE_ITEM',
    ADD_ITEM: 'ADD_ITEM',
    SET_ITEMS: 'SET_ITEMS',

    SET_ITEM: 'SET_ITEM',
    UPDATE_ITEM_ATTRIBUTE: 'UPDATE_ITEM_ATTRIBUTE',

    SET_PRICE_SETTING: 'SET_PRICE_SETTING',
    SET_ORDER: 'SET_ORDER',
    SET_RECENTLY_VIEWED_LOGO: 'SET_RECENTLY_VIEWED_LOGO',
    SET_CONDITION: 'SET_CONDITION',
    SET_M_INDUSTRIES: 'SET_M_INDUSTRIES',
    SET_M_COLORS: 'SET_M_COLORS',
    SET_M_TASTES: 'SET_M_TASTES',
    SET_M_ALPHABETS: 'SET_M_ALPHABETS',
    SET_FAVORITE_COUNT: 'SET_FAVORITE_COUNT',
    SET_KEYWORD_RECENTLY: 'SET_KEYWORD_RECENTLY',
    SET_OVERLAY: 'SET_OVERLAY',
    SET_ACTION_SEARCH: 'SET_ACTION_SEARCH',

    PRODUCT_MATERIAL_TYPE: 1,
    PRODUCT_WORK_TYPE: 2,
    LANGUAGES: {
        'vi': 'vi',
        'en': 'en',
        'ja': 'ja'
    },

    SET_CONTACT_DATA: 'SET_CONTACT_DATA',
    SET_PAGE_LOGO_ADMIN:'SET_PAGE_LOGO_ADMIN',

    SET_TOTAL_AMOUNT: 'SET_TOTAL_AMOUNT',
}
