export default {
    UPDATE_SITUATION: 'UPDATE_SITUATION',
    DELETE_SITUATION: 'DELETE_SITUATION',
    ADD_SITUATION: 'ADD_SITUATION',
    SET_SITUATIONS: 'SET_SITUATIONS',

    REQUEST_STATUS_ESTIMATE: 1,
    REQUEST_STATUS_RECEIVED: 2,
    REQUEST_STATUS_CONFIRMED: 3,
    REQUEST_STATUS_COMPLETE: 5,

    REQUEST_UPDATE_CONDITION: 'REQUEST_UPDATE_CONDITION',
    PRODUCT_UPDATE_CONDITION: 'PRODUCT_UPDATE_CONDITION',
}
